openapi: 3.0.3
info:
  title: Id Watchlist API
  description: The ID Network Watchlist API allows the customer to search and store identity attributes involved with high risk activities. The API helps the customers to make decisions based upon a returned threat level for each field.
  contact:
    name: API Support
    email: apisupport@mastercard.com
    url: https://developer.mastercard.com/support
  version: '0.0.2'
servers:
  - url: 'https://api.mastercard.com.au/idwatchlist'
    description: Production server (uses live data)
  - url: 'https://sandbox.api.mastercard.com.au/idwatchlist'
    description: Sandbox server (testing environment)
tags:
  - name: Fraud Data
    description: Fraud data related operations.

paths:
  /fraud-signal-data:
    post:
      summary: >-
        Create a new Fraud data
      tags:
        - Fraud Data
      responses:
        '201':
          $ref: '#/components/responses/FraudSuccess'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
      description: >-
        Allow customers to save fraud data into the database to be consulted later.
      operationId: createFraudData
      requestBody:
        $ref: '#/components/requestBodies/FraudData'
  /fraud-signal-data-searches:
    post:
      summary: >-
        Search for Fraud Data
      tags:
        - Fraud Data
      responses:
        '200':
          $ref: '#/components/responses/FraudSuccessSearch'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
      description: >-
        Allows to search Fraud Data.
      operationId: searchFraudData
      requestBody:
        $ref: '#/components/requestBodies/FraudSearchData'
components:
  schemas:
    FraudData:
      required:
        - fraudSignals
        - originatedSource
        - originatedSystem
      type: object
      properties:
        originatedSystem:
          description: Originated system, from where the call happened.
          minLength: 3
          maxLength: 30
          type: string
          example: Optus
        originatedSource:
          description: Originated source of the fraud data.
          example: RISKCENTER
          type: string
          minLength: 3
          maxLength: 30
        originatedSystemTransactionId:
          description: A random 128-bit. UUID representing the transaction.
          example: 28eae1aa-6744-433e-879d-7da48d63e89a
          type: string
          minLength: 36
          maxLength: 36
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        fraudSignals:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/FraudSignals'
          description: The list of fraud data signals to be persisted.
    FraudSignals:
      required:
        - fraudSignalIdentifierData
      type: object
      properties:
        fraudSignalIdentifierData:
          $ref: '#/components/schemas/FraudIdentifierData'
    FraudIdentifierData:
      required:
        - scoreBand
      type: object
      properties:
        scoreBand:
          description: Score band flag. Values can be RED or YELLOW. Indicates the risk level of the entity.
          type: string
          example: YELLOW
          pattern: '^(RED|YELLOW)$'
          minLength: 3
          maxLength: 6
        scoreValue:
          description: Score from nudetect.
          example: 12
          type: integer
          format: int32
          minimum: 1
          maximum: 1000
          pattern: '^([1-9][0-9]{0,2}|1000)$'
        ipAddress:
          description: IP of the user.
          example: 1.2.3.4
          type: string
          minLength: 1
          maxLength: 15
          pattern: '^(\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$'
        documentId:
          description: ID of document.
          example: 'DID1234'
          type: string
          minLength: 1
          maxLength: 50
          pattern: '^[0-9a-zA-Z\-]{1,50}$'
        name:
          description: Name of the user.
          example: 'John Smith'
          type: string
          minLength: 1
          maxLength: 255
          pattern: '^[a-zA-Z\s ,.''‘’-]{1,255}$'
        dob:
          description: Date of birth of user. Please use the format YYYY-MM-DD.
          example : '1980-01-01'
          type: string
          minLength: 1
          maxLength: 10
          pattern: '^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$'
        nationalId:
          description: ID of the country to which the user belongs.
          example: 123456789
          type: string
          minLength: 1
          maxLength: 50
          pattern: '^[0-9a-zA-Z\-]{1,50}$'
        phoneNumber:
          description: Phone number of the user.
          example: 3031232233
          type: string
          minLength: 1
          maxLength: 14
          pattern: '^[1-9]\d{2,14}$'
        address:
          description: Address of the user.
          example: '123 Main St'
          type: string
          minLength: 1
          maxLength: 255
          pattern: '^[a-zA-Z0-9\s ,.''‘’-]{1,255}$'
        ndDeviceId:
          description: ID of the device. The NuData Device ID is a device identifier that uses elements of the device configurations or tokens.
          example: '209834a3-5b52-4425-8441-ae00334030e2'
          type: string
          minLength: 1
          maxLength: 36
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
    FraudDataResultSearch:
      type: object
      properties:
        scoreBand:
          description: Score band flag. Values can be RED or YELLOW. Indicates the risk level of the entity.
          type: string
          example: YELLOW
          pattern: '^(RED|YELLOW)$'
          minLength: 3
          maxLength: 6
        fraudDateTime:
          description: 'Time that event occurred'
          example: '2021-12-02T21:47:03.575Z'
          type: string
          minLength: 1
          maxLength: 24
    FraudSearchData:
      minProperties: 1
      type: object
      properties:
        ipAddress:
          description: IP of the user.
          example: 1.2.3.4
          type: string
          minLength: 1
          maxLength: 15
          pattern: '^(\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$'
        documentId:
          description: ID of document.
          example: 'DID1234'
          type: string
          minLength: 1
          maxLength: 50
          pattern: '^[0-9a-zA-Z\-]{1,50}$'
        name:
          description: Name of the user.
          example: 'John Smith'
          type: string
          minLength: 1
          maxLength: 255
          pattern: '^[a-zA-Z\s ,.''‘’-]{1,255}$'
        dob:
          description: Date of birth of user. Please use the format YYYY-MM-DD.
          example : '1980-01-01'
          type: string
          minLength: 1
          maxLength: 10
          pattern: '^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$'
        nationalId:
          description: ID of the country to which the user belongs.
          example: 123456789
          type: string
          minLength: 1
          maxLength: 50
          pattern: '^[0-9a-zA-Z\-]{1,50}$'
        phoneNumber:
          description: Phone number of the user.
          example: 3031232233
          type: string
          minLength: 1
          maxLength: 14
          pattern: '^[1-9]\d{2,14}$'
        address:
          description: Address of the user.
          example: '123 Main St'
          type: string
          minLength: 1
          maxLength: 255
          pattern: '^[a-zA-Z0-9\s ,.''‘’-]{1,255}$'
        ndDeviceId:
          description: ID of the device. The NuData Device ID is a device identifier that uses elements of the device configurations or tokens.
          example: '209834a3-5b52-4425-8441-ae00334030e2'
          type: string
          minLength: 1
          maxLength: 36
          pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'

    ErrorResponse:
      required:
        - Errors
      type: object
      description: The error response model used by all our API endpoints.
      properties:
        Errors:
          required:
            - Error
          type: object
          description: The error response model used by all our API endpoints.
          properties:
            Error:
              description: List of error objects.
              minItems: 1
              type: array
              items:
                type: object
                properties:
                  Source:
                    type: string
                    description: The source of the problem. That is where the error occurred.
                    example: watchlist
                  ReasonCode:
                    type: string
                    description: A code defining the error, as defined in the documentation.
                    example: NOT_FOUND
                  Description:
                    type: string
                    description: A description for this specific occurrence of the above ReasonCode.
                    example: The requested resource could not be found.
                  Recoverable:
                    type: boolean
                    description: Whether retrying this request could result in a successful response.
                    example: false
                  Details:
                    type: string
                    description: >-
                      More details of this specific error. This is an optional field and is sometimes used to give a more comprehensive description of the error that has occurred when required.
                    example: No handler found for POST /watchlist/xxxx
  responses:
    FraudSuccessSearch:
      description: Success
      headers:
        X-Transaction-ID:
          schema:
            type: string
          description: A random 128-bit UUID representing the transaction.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FraudDataResultSearch'
          examples:
            FraudSuccessSearchExample:
              $ref: '#/components/examples/FraudSuccessSearchExample'

    FraudSuccess:
      description: Success
      headers:
        X-Transaction-ID:
          schema:
            type: string
          description: A random 128-bit UUID representing the transaction.
    BadRequestError:
      description: Something was wrong with the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            BadRequestErrorExample:
              $ref: '#/components/examples/BadRequestErrorExample'
    ForbiddenError:
      description: Forbidden.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            ForbiddenExample:
              $ref: '#/components/examples/ForbiddenExample'
  requestBodies:
    FraudData:
      description: Fraud Data that is going to be saved in the database.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FraudData'
    FraudSearchData:
      description: Criteria for searching fraud data.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FraudSearchData'
  examples:
    ForbiddenExample:
      value:
        Errors:
          Error:
            - Source: watchlist
              ReasonCode: FORBIDDEN
              Description: Access denied
              Recoverable: false
    BadRequestErrorExample:
      value:
        Errors:
          Error:
            - Source: watchlist
              ReasonCode: VALIDATION_ERROR
              Description: 'Invalid value null for originatedSource'
              Recoverable: false
    FraudSuccessSearchExample:
      value:
        scoreBand: YELLOW
        fraudDateTime: '2021-12-02T21:47:03.575Z'